"""Build the pattern catalog and update the root manifest.

This script intentionally writes ASCII markdown so the catalog is readable in
PowerShell, GitHub, and by AI agents without code-page surprises.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path


LIBRARY_ROOT = Path(__file__).resolve().parents[1]
PATTERNS_DIR = LIBRARY_ROOT / "patterns"
CATALOG_PATH = LIBRARY_ROOT / "CATALOG.md"
MANIFEST_PATH = LIBRARY_ROOT / "manifest.json"


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def compact_requirements(manifest: dict) -> str:
    chunks: list[str] = []
    tags = manifest.get("required_tags") or []
    dbs = manifest.get("required_dbs") or []
    instance_db = manifest.get("required_instance_db") or ""
    data_types = manifest.get("required_data_types") or []

    if tags:
        tag_text = ", ".join(
            f"{item.get('name', '?')}:{item.get('type', '?')}" for item in tags
        )
        chunks.append(f"tags={tag_text}")
    if dbs:
        formatted_dbs: list[str] = []
        for item in dbs:
            if isinstance(item, dict):
                formatted_dbs.append(f"{item.get('name', '?')}:{item.get('type', '?')}")
            else:
                formatted_dbs.append(str(item))
        chunks.append("dbs=" + ", ".join(formatted_dbs))
    if instance_db:
        chunks.append(f"instance_db={instance_db}")
    if data_types:
        chunks.append("types=" + ", ".join(str(x) for x in data_types))
    return "<br>".join(chunks) if chunks else "-"


def collect_patterns() -> list[dict]:
    rows: list[dict] = []
    if not PATTERNS_DIR.exists():
        return rows

    for category_dir in sorted(p for p in PATTERNS_DIR.iterdir() if p.is_dir()):
        for pattern_dir in sorted(p for p in category_dir.iterdir() if p.is_dir()):
            manifest_path = pattern_dir / "manifest.json"
            manifest = load_json(manifest_path) if manifest_path.exists() else {}
            rel_pattern = pattern_dir.relative_to(LIBRARY_ROOT).as_posix()
            rel_xml = (pattern_dir / "pattern.xml").relative_to(LIBRARY_ROOT).as_posix()
            rows.append(
                {
                    "category": category_dir.name,
                    "name": pattern_dir.name,
                    "instruction": manifest.get("block_instruction_name", pattern_dir.name),
                    "status": manifest.get("tested_status", "unknown"),
                    "xml": rel_xml if (pattern_dir / "pattern.xml").exists() else "-",
                    "folder": rel_pattern,
                    "requirements": compact_requirements(manifest),
                }
            )
    return rows


def write_catalog(rows: list[dict]) -> None:
    category_counts: dict[str, int] = {}
    for row in rows:
        category_counts[row["category"]] = category_counts.get(row["category"], 0) + 1

    lines: list[str] = []
    lines.append("# TIA V18 XML Pattern Catalog")
    lines.append("")
    lines.append("Generated by `tools/build_catalog.py`.")
    lines.append("")
    lines.append(f"- Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"- Total patterns: {len(rows)}")
    lines.append("")
    lines.append("## Category Summary")
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|---|---:|")
    for category, count in sorted(category_counts.items()):
        lines.append(f"| `{category}` | {count} |")
    lines.append("")
    lines.append("## Patterns")
    lines.append("")
    lines.append("| Category | Pattern | Instruction | Status | Requirements | XML |")
    lines.append("|---|---|---|---|---|---|")
    for row in rows:
        xml_link = "-" if row["xml"] == "-" else f"[pattern.xml]({row['xml']})"
        lines.append(
            "| "
            f"`{row['category']}` | "
            f"`{row['name']}` | "
            f"`{row['instruction']}` | "
            f"`{row['status']}` | "
            f"{row['requirements']} | "
            f"{xml_link} |"
        )
    lines.append("")
    lines.append("## Agent Reminder")
    lines.append("")
    lines.append("- Reuse these patterns before writing any new XML.")
    lines.append("- Missing pattern means export from TIA Portal V18 first or add TODO.")
    lines.append("- For current contest projects, use Modbus TCP instead of GET/PUT.")
    lines.append("- For PID, prefer `PID_Compact` version `1.2` plus `sRet.i_Mode` guard.")

    CATALOG_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def update_root_manifest(rows: list[dict]) -> None:
    manifest = {
        "name": "TIA_V18_XML_Pattern_Library",
        "description": "Reusable SimaticML XML patterns for TIA Portal V18 S7-1200 LAD generation.",
        "tia_version": "V18",
        "plc_family": "S7-1200",
        "language": "LAD",
        "patterns_count": len(rows),
        "categories": {},
        "last_catalog_build": datetime.now().isoformat(timespec="seconds"),
        "policy": {
            "do_not_invent_missing_xml": True,
            "prefer_modbus_tcp_over_get_put": True,
            "pid_compact_version": "1.2",
        },
    }
    for row in rows:
        manifest["categories"][row["category"]] = manifest["categories"].get(row["category"], 0) + 1

    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    rows = collect_patterns()
    write_catalog(rows)
    update_root_manifest(rows)
    print(f"Built catalog with {len(rows)} patterns: {CATALOG_PATH}")
    print(f"Updated manifest: {MANIFEST_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
